name: Auto Update Pull Requests Reusable

on:
  workflow_call:
    secrets: 
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true
      sr_token:
        required: true

jobs:
  auto-update-pr:
    name: auto-update-pr
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.SR_TOKEN }}"
