name: Commit Issue Commenter

on:
  workflow_call:
    secrets: 
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true
      github_token:
        required: true
        
jobs:
  checkCommit:
    name: Comment From Commit
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: adamzolyak/commit-issue-commenter-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
