name: Global Workflow To Rule Them All Reusable

on:
  workflow_call:
    secrets: 
      sr_token:
        required: true

jobs:
  replicate_changes:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - run: git config --global --replace-all url."https://oauth2:${{ secrets.SR_TOKEN }}@github.com".insteadOf https://github.com
        - name: Replicating global workflow
          uses: derberg/copy-files-to-other-repositories@v1.0.0
          if: github.event.repository.name == 'template'
          with:
            github_token: "${{ secrets.SR_TOKEN }}"
            patterns_to_include: '.github/workflows'
            patterns_to_ignore: '.github/workflows/global-workflow.yml'
            repos_to_ignore: argocd-example-apps,cdktf-aws-stack-ccm,.github,aws-iac,aws-cdktf-multi-support
            committer_username: srdevops
            committer_email: 29293764+srdevops@users.noreply.github.com
            commit_message: "ci: update global workflows"
