name: pull-request-lint-reusable

on:
  workflow_call:
    secrets: 
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true
      github_token:
        required: true
        
jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: amannn/action-semantic-pull-request@v5.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          validateSingleCommit: true
          validateSingleCommitMatchesPrTitle: true
