name: Remote Reausable Workflow

on:
  workflow_call:
    inputs:
      tag: 
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Write something to log
        run: echo "I am a reusable workflow ${{inputs.tag}}- main branch"
